image:
  name: 760680488142.dkr.ecr.us-east-1.amazonaws.com/dev/automation-cypress:latest
  aws:
    access-key: $AWS_ACCESS_KEY
    secret-key: $AWS_SECRET_KEY

definitions:
  caches:
    sonar: ~/.sonar/cache # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &build-test
        name: Build and unit test
        caches:
          - node
        script:
          - npm install --quiet --legacy-peer-deps
          - npm run coverage -- --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox
    - step: &build-test-custom-sonar
        name: Build, test and analyze on SonarCloud (Custom run)
        caches:
          - node
        script:
          - npm install --quiet --legacy-peer-deps
          - npm run sonar
    - step: &build-test-sonarcloud
        size: 2x
        name: Build, test and analyze on SonarCloud
        caches:
          - node
          - sonar
        script:
          - npm install --quiet --legacy-peer-deps
          - npm run coverage -- --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox
          - pipe: sonarsource/sonarcloud-scan:1.4.0
            variables:
              SONAR_TOKEN: ${SONAR_TOKEN}
              EXTRA_ARGS: '-Dsonar.branch.name="$BITBUCKET_BRANCH"'

pipelines:
  pull-requests:
    "**":
      - step: *build-test-custom-sonar
  branches:
    "{hotfix/*}":
      - step: *build-test
    "{bugfix/*}":
      - step: *build-test
    "{feature/*}":
      - step: *build-test
    "{develop,qa}":
      - step: *build-test-custom-sonar
    "{release/*}":
      - step: *build-test-custom-sonar
    "{staging}":
      - step: *build-test-custom-sonar
    "{master}":
      - step: *build-test-custom-sonar
